### ISSUE TITLE
Do you still need 1 puck per vent?

### ISSUE THREAD

**Issue by rjf026** [RobertD502/home-assistant-flair#25]
I have 4 ecobee sensors and 30ish Xiaomi BT sensors throughout my house that are connected to HA. I’d like to use my Xiaomi sensors to help control the Flair vents instead of getting Flair pucks and effectively duplicating my existing temperature and humidity sensors.

**Comment by RobertD502** [comment]
You DON'T need 1 puck per vent. You do, however, need at least 1 puck (you may need more, but I'll elaborate more on that later).

The reason that you need at least 1 puck for **a single or multiple** vents is because a puck is needed to act as a gateway for the vents - a gateway to Flair's servers and the hardware that sends commands to vents. The vents don't have WiFi support, so, they wouldn't be able to connect to Flair's servers themselves/receive commands from the API without at least one puck.

The reason I say at least one puck is because the amount of pucks you will need will depend on the signal strength between the puck and your vents. For example, I have 1 Puck and 4 vents. This set up works because the vents themselves are close enough to maintain a connection (via RF) to the single puck. If I were to place vents inside of my home that are too far away from the puck to maintain a connection to it, I would need to invest in another puck and place it at the appropriate distance to the vent(s) in question.

Regarding duplicating your existing temp and humidity sensors....you do not need to have the Flair puck do any of the temp/humidity sensing for your setup. I also have ecobee sensors. What I have done is: Created rooms within the flair app and assigned the related vents to them. I then assigned, also within the Flair app, ecobee sensors to the Flair rooms in which the Flair vents and related ecobee sensors are located. I then created a separate Flair room (in the app) and placed JUST the Flair puck into it. By doing so, for rooms in which the Flair vents are located in, only the ecobee sensors are used to determine if/when the flair vents located in the same Flair room should open/close. Measurements from the puck are never taken into account as it resides in its own Flair room in the app (this room has no vents associated with it). In this scenario, the puck simply acts as a gateway that relays the open/close commands to the vents.

Since Flair rooms are virtual rooms that you have created, you can have a puck be physically located in a room where you have Flair vents, but have the puck assigned to a separate Flair room. For example: Let's say I have 4 Flair vents and 1 puck. 2 of the vents are located physically in my office and two vents are placed in the bedroom. Then let's say that I discover that the Flair puck has the best connection to all 4 vents when it is physically located in the bedroom. Now, just because it is physically located in the bedroom doesn't mean I need to assign the Puck device, in the Flair app, to the Flair room titled "Bedroom" that I created. Instead, if I want only the ecobee sensors to determine the temperature in the bedroom and office, I would assign the puck to another Flair room titled "Hallway", for example.


Since I personally only use ecobee sensors to control vents, and with ecobee sensors directly supported in the app, I just have Flair handle the opening and closing of my vents based on the ecobee sensor readings. However, if you want to use sensors which are not natively supported by the Flair app to control opening and closing the vents, you would need to set control of your vents (done in the Flair app) to "Manual" mode. You would then use this integration to pull in your Flair vents into Home Assistant. After having done so, you will need to create your own automations that use temp/humidity readings from the unsupported sensors (unsupported natively in the Flair app, but supported/exposed within Home Assistant), to control opening and closing Flair vents. 


Hope this helped clear up some things for you.

**Comment by rjf026** [comment]
Thanks! This is very helpful information. I may be able to get by with just 1 puck in a central location, but TBD. First I need to order more vents. I started with 1 puck and 1 vent to see how things worked, and so far I like what I see. I need to figure out how to modify some existing 8x6 vents, since flair doesn’t offer that size yet. Ideally I’ll play around with making my own automations in HA to use my existing temp sensors, but if that doesn’t work out, I’ll have to bite the bullet and buy another 6 or so sensors from Ecobee or additional pucks. Thanks!

**Comment by RobertD502** [comment]
No problem. Hope it works out for you!
