### ISSUE TITLE
Feature: Create climate device for main house

### ISSUE THREAD

**Issue by dkmcgowan** [RobertD502/home-assistant-flair#36]
The main house could also have a climate entity, you have the set point and the mode, gives options on ways to display the entities

**Comment by RobertD502** [comment]
Bear with me as I'm a bit confused as to what you're asking for here.

Are you asking for the Structure Mode (Heating/cooling) and Home set point entities to be combined into a single Climate entity?

If that is the case there are some limitations as to what the entity can show/do:

There will be no current temperature reading since this is for the entire structure.

If the structure is set to manual mode: This entity will be unavailable

If the structure is set to auto mode & set point controller is set to thermostat: Only changing heating/cooling is possible

If the structure is set to auto mode & set point controller is set to Flair app: Can change heating/cool and target temperature

**Comment by dkmcgowan** [comment]
Good points, I was talking about the structure mode and home set point
being pushed into a climate entity.  There is a current temperature right?
The home set point has a current value, so when I display home set point in
like an entities card I can see current value and can move it up or down.
I get your point on manual mode, I haven't used that one much.

Looks like to complicated, I get it, thanks for responding...

**Comment by RobertD502** [comment]
So the Home set point isn't the current temperature. Rather, it is the "target" temperature that you want your system to reach. This is because the current temperature will be different based on what room you're looking at. The structure itself doesn't have a "current" temperature.

**Comment by dkmcgowan** [comment]
Yep, I get it, I was really just trying to more easily use a better UI
control to set the home point and change the mode with mushroom cards and
not rely on the entities card to be honest, not really wanting the climate
entity really but a means to an end

**Comment by RobertD502** [comment]
I actually think it is a great idea and decreases the number of entities. Just added the climate entity to release 0.1.3 and have removed the entities Structure mode and Home set point since they are combined into that single climate entity.

**Comment by dkmcgowan** [comment]
That's awesome, just tested and it worked great!

Got me thinking on something I just never did in the Flair app but would be
easier in HA integration, if the main structure is say on Cool and you
turned a room into Heat what does Flair even do?  Seems like that wouldn't
do anything right?

**Comment by dkmcgowan** [comment]
Makes sense and I think actually turns into a feature
