### ISSUE TITLE
Request for reported vent position

### ISSUE THREAD

**Issue by level451** [RobertD502/home-assistant-flair#44]
Hi,
I have an issue where a couple of my vents show open, both in HA and the flair app, but are actually closed even after several hours. If I go into the vent stats, I can see that they are still closed, and that seems to be accurate. When I open or close an event by a service call, it instantly changes the value even if the vent did not move. Is there a way to the reported (by the vent) position currently? If not, could we add something like reported vent position? I believe it is in the api. I could use the information to set and automation to look for open vents that are reporting closed after 5 min, and vice-versa.

Thanks - the integration is awesome!

**Comment by RobertD502** [comment]
The reason this happens is because calls are made to Flair's servers which is then routed to your puck. It is then the responsibility of the puck to relay that message to the vent(s) which is why you're seeing it in both Home Assistant and the Flair app (which also relies on their API).

If I was in your shoes I'd focus on figuring out why your vents aren't responding to the command. One reason could be they are too far from the puck that controls them.

**Comment by level451** [comment]
I also monitor the rssi, and its good(-76). I have quite a few vents, and this morning 2 of them were in the wrong position today. The vents are great since they know and report their position. Because the reported position is available, I figured it would be nice to have (data nerd). My alternative is the monitor room vs setpoint error and alarm off of that.
I did a reset of the vent yesterday and it happened again today. I have a support ticket in.

With reporting the actual vent position, you could add it as a disabled entity, and only users who were interested would enable it- like zha does with rssi.

Thanks - Todd

**Comment by RobertD502** [comment]
Noted. I have to agree with you that it would be useful. Was just making sure you wouldn't be using something like this to rely on long term as the root of the problem needs to be fixed. 

I'll have to do some testing to see the exact amount of lag there is between the logs and the vents physically opening/closing. After that the backend needs to be updated to also target the log endpoint for each vent a user has followed by creating a sensor within the HA code. All of that is to say it will be a minute before I get to it as I have some other stuff on my plate at the moment.

**Comment by level451** [comment]
That would be awesome. It seems to update at the next check-in from the vent to the puck after the command was executed.
So - command 1-60 seconds vent moves - 30-60s later data is updated. That's just from a few quick tests. I'm a nodejs/javascript guy so the code is I little strange to me, but if I can help in anyway I would love to.
Thanks

**Comment by RobertD502** [comment]
Great news. Poked around a little bit and realized I am already pulling in the needed data for vents in the backend. The graph page on the app corresponds to the sensor-readings endpoint for each vent. Instead of making a call to this new endpoint and extracting the most recent data point, I realized the current-reading endpoint that I am already fetching corresponds to the most recent data point in the sensor-readings endpoint.

I'll go ahead and add a new diagnostic sensor to the HA integration code and get that released out.

**Comment by level451** [comment]
That is great - I really apricate the effort you have put in. This is a great integration.

**Comment by RobertD502** [comment]
Thanks for the feedback!

Just pushed out version 0.1.7 that includes the changes. Restarting Home Assistant should get the new release to show up.

**Comment by level451** [comment]
Works great!!! Updates faster than I thought. You are awesome!
Todd
