### ISSUE TITLE
Vents (covers) become unavailable

### ISSUE THREAD

**Issue by sstratoti** [RobertD502/home-assistant-flair#48]
Good morning!

I've been seeing some issues with my cover entities where they go unavailable. 

![image](https://user-images.githubusercontent.com/1392597/217531198-996ed7ec-0c75-43dc-b8ca-5af45fa7c6e5.png)

In my node red flow I'm checking the status of the cover before I call an open/close. Figured I didn't want to trigger an open if it's already open. 

Does this rationale make sense? Or would calling for a cover/open when it's already open not matter in the grand scheme of things? I ask because if theres nothing that can be done with flair covers becoming unavailable (api limiting or something) maybe I can just automate around it. 

Thank you!

**Comment by RobertD502** [comment]
Hi Stephen,

Vents (covers) are set to become unavailable when the API is reporting them as being offline. This is more than likely due to your vent losing connection to the puck it connects to and not any API rate limiting.

If you were to send an open command while the cover is already open, it wouldn't cause any problems like the cover closing or something.

I'm assuming you're already doing this, but one way of catching the error is to use the catch node (I forget if that is what it is called, but it is red in appearance) which will be activated when the service call fails - then have it go to a blocking node of your choice that wait to make the call again once the vent is reported as being available again.

Other than that, you can investigate if your puck needs to be repositioned for a better connection to the vent.

**Comment by RobertD502** [comment]
@sstratoti Any other concerns?

**Comment by sstratoti** [comment]
Hi Robert! Thanks for the reply. I don't think so. I'll review/investigate and will report back if I have any additional questions.
