### ISSUE TITLE
Feature request: Show average home temp for the Flair Structure current temp 

### ISSUE THREAD

**Issue by MasterDevwi** [RobertD502/home-assistant-flair#68]
The Flair Structure climate entity currently doesn’t display the current temperature since the structure is for the entire house.

Rather than omit the current temp it would be awesome if the Flair Structure entity could show either the average temp for the house (across all pucks) or better yet a range (low and high end). This would make it easy to show the overall home temperature when looking at the structure’s climate card.

**Comment by RobertD502** [comment]
Hi!

The Structure entities are meant to display/control what the Flair API returns for the structure. Although this is a great idea, I believe that it falls more under a personal customization - if you want to get an average temperature, I'd recommend using Home Assistant's [group](https://www.home-assistant.io/integrations/group/) feature which was introduced in 2023.9 to average the temperatures from the rooms you have temp readings from.

**Comment by MasterDevwi** [comment]
Thanks Robert. The way I was thinking about it, the Flair Structure entity represents the climate for the overall household, so showing the average temperature (alongside the ability to control the set point temperature for the housse) would make sense. It would also allow users to add this climate entity to their dashboard and put room-specific controls elsewhere if needed. As it currently stands, you have to have a separate card to represent the current temp in the house since the climate entity doesn't support it.

But you're right in that Flair technically doesn't report a temperature for the whole house, so this would be a small delta. Anyway, thanks for considering it.

**Comment by RobertD502** [comment]
Completely reasonable request! Aside from Flair not reporting a structure temperature, I stayed away from adding a current temp to the climate entity due to varying setups - some use Flair vents without compatible sensors in the Flair "rooms" so they wouldn't have a temperature to display. Another reason is due to the possibility of user confusion (e.g., "I have set the temperature to 72, but the climate entity's current temp reading is never reaching the set temperature"). This one in particular can be solved by adding a note in the documentation, but a lot of users are bad about reading the docs.

I think your suggestion is a good one - I'll ponder a little bit over what the best way forward would be and handling some of the edge cases.

Side note: I believe you know my partner - Ellen from Edge GTM says hello and hopes you are doing well 🐰🥚.

**Comment by MasterDevwi** [comment]
Yeah, that's totally fair! I appreciate you considering it at least. In the meantime, maybe I'll just create a separate entity that can open up the thermostat controls in a custom more-info dialog.

Also, no way! What a small world. 🤯 Please tell her hi for me! That project was _so_ much fun to work on together. I hope she's doing well too!

**Comment by MasterDevwi** [comment]
Also, I forgot to say this earlier, but thank you for building this integration! I absolutely love it.
