### ISSUE TITLE
Feature Request Turning off room thermostat should mark room as away

### ISSUE THREAD

**Issue by snackpack85** [RobertD502/home-assistant-flair#88]
Good afternoon!

If I'm not mistaken, the current action when turning a room climate entity off mirrors the "off" back to the structure climate entity, causing the entire house to no longer heat/cool.

Is it possible/ does it make sense to have toggling a climate entity off make the room inactive instead? When using climate cards in dashboards, it would make everything much simpler.

**Comment by RobertD502** [comment]
I get what you're saying, but it doesn't align with how Flair handles rooms. For example, when using the Flair app, setting a room to inactive doesn't change the heat/cool setting of the room and you can't even select a mode. The integration attempts to mirror this concept, but is hindered by Home Assistant requirements:

The room climate entity is essentially only there to handle setting a temperature. The heat/cool/auto mode for the room climate entity only exists because Home Assistant requires a climate entity to present that the mode option - as a result this has been made into a shortcut for handling if a structure is in heat/cool/auto. If it wasn't a climate entity requirement by Home Assistant, I wouldn't even have the Flair room entity present the option as this would be a 1:1 of how Flair handles rooms.

For handling setting a room to active/inactive, use the select entity that was specifically made for said function.
